import { BASE_API_URL } from "./env";

export const PET_API = `${BASE_API_URL}/pet`;
export const SPECIES_API = `${BASE_API_URL}/species`;
export const RACE_API = `${BASE_API_URL}/race`;
export const AUTH_API = `${BASE_API_URL}/auth`;
export const CLIENT_API = `${BASE_API_URL}/client`;
export const ROLE_API = `${BASE_API_URL}/role`;
export const PRODUCT_API = `${BASE_API_URL}/product`;
export const PRODUCT_PRICE_API = `${BASE_API_URL}/product-price`;
export const VACCINE_API = `${BASE_API_URL}/vaccine`;
export const VACCINE_MANUFACTURER_API = `${BASE_API_URL}/vaccine-manufacturer`;
export const VACCINE_REGISTRY_API = `${BASE_API_URL}/vaccine-registry`;
export const VACCINE_BATCH_API = `${BASE_API_URL}/vaccine-batch`;
export const EMPLOYEE_API = `${BASE_API_URL}/employee`;
export const WORK_POSITION_API = `${BASE_API_URL}/work-position`;
export const STOCK_API = `${BASE_API_URL}/stock`;
export const STOCK_DETAILS_API = `${BASE_API_URL}/stock-detail`;
export const PROVIDER_API = `${BASE_API_URL}/provider`;
export const TAG_API = `${BASE_API_URL}/tag`;
export const MOVEMENTS_API = `${BASE_API_URL}/movement`;
export const PURCHASE_API = `${BASE_API_URL}/purchase`;
export const PURCHASE_DETAIL_API = `${BASE_API_URL}/purchase-detail`;
